package controlplane

import (
	"context"
	"fmt"
	"log"
	"sync"
	"time"

	"github.com/foreman/foreman/internal/eventbus"
	"github.com/foreman/foreman/internal/schemas"
	"github.com/foreman/foreman/internal/statestore"
)

// Audit appends an entry to the audit trail. No-op if the store is nil (memory-only mode).
// Exported so the coordinator can log agent events and approvals.
func (cp *ControlPlane) Audit(ctx context.Context, sessionID, action string, metadata map[string]any) {
	if cp.store == nil {
		return
	}
	entry := statestore.AuditEntry{
		ID:        0, // auto-generated by the database
		SessionID: sessionID,
		Action:    action,
		Target:    sessionID,
		Metadata:  metadata,
		CreatedAt: time.Now(),
	}
	if err := cp.store.AppendAuditEntry(ctx, entry); err != nil {
		log.Printf("controlplane: audit: %v", err)
	}
}

var validTransitions = map[schemas.SessionStatus][]schemas.SessionStatus{
	schemas.StatusCreated:    {schemas.StatusAllocating, schemas.StatusFailed},
	schemas.StatusAllocating: {schemas.StatusRunning, schemas.StatusFailed},
	schemas.StatusRunning:    {schemas.StatusApproval, schemas.StatusCompleted, schemas.StatusCancelling, schemas.StatusFailed},
	schemas.StatusApproval:   {schemas.StatusRunning, schemas.StatusCancelling, schemas.StatusFailed},
	schemas.StatusCancelling: {schemas.StatusFailed, schemas.StatusCompleted},
}

type Session struct {
	ID          string
	Status      schemas.SessionStatus
	TaskID      string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	mu          sync.RWMutex
}

type ControlPlane struct {
	bus      eventbus.EventBus
	store    statestore.StateStore // optional, nil = memory-only mode
	sessions map[string]*Session
	mu       sync.RWMutex
}

func New(bus eventbus.EventBus, store statestore.StateStore) *ControlPlane {
	return &ControlPlane{
		bus:      bus,
		store:    store,
		sessions: make(map[string]*Session),
	}
}

func (cp *ControlPlane) CreateSession(ctx context.Context, sessionID, taskID, description string) error {
	s := &Session{
		ID:          sessionID,
		Status:      schemas.StatusCreated,
		TaskID:      taskID,
		Description: description,
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	}

	// Persist to StateStore first so a failure prevents the in-memory write.
	if cp.store != nil {
		if err := cp.store.CreateSession(ctx, statestore.Session{
			ID:          s.ID,
			TaskID:      s.TaskID,
			Description: s.Description,
			Status:      string(s.Status),
			CreatedAt:   s.CreatedAt,
			UpdatedAt:   s.UpdatedAt,
		}); err != nil {
			return fmt.Errorf("store create session: %w", err)
		}
	}

	cp.mu.Lock()
	cp.sessions[sessionID] = s
	cp.mu.Unlock()

	cp.Audit(ctx, sessionID, "session.created", map[string]any{
		"task_id": taskID,
		"status":  string(s.Status),
	})
	return cp.emit(ctx, s, schemas.EvSessionCreated)
}

func (cp *ControlPlane) Transition(ctx context.Context, sessionID string, to schemas.SessionStatus) error {
	cp.mu.Lock()
	s, ok := cp.sessions[sessionID]
	cp.mu.Unlock()
	if !ok {
		return fmt.Errorf("session %s not found", sessionID)
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	allowed, ok := validTransitions[s.Status]
	if !ok {
		return fmt.Errorf("no transitions defined from %s", s.Status)
	}
	valid := false
	for _, t := range allowed {
		if t == to {
			valid = true
			break
		}
	}
	if !valid {
		return fmt.Errorf("invalid transition %s -> %s", s.Status, to)
	}

	from := string(s.Status)
	s.Status = to
	s.UpdatedAt = time.Now()

	// Persist status change to StateStore.
	if cp.store != nil {
		if err := cp.store.UpdateSessionStatus(ctx, sessionID, string(to), s.UpdatedAt); err != nil {
			log.Printf("controlplane: store update session %s status: %v", sessionID, err)
		}
	}

	var evtType schemas.EventType
	switch to {
	case schemas.StatusAllocating:
		evtType = schemas.EvSessionAllocating
	case schemas.StatusRunning:
		evtType = schemas.EvSessionRunning
	case schemas.StatusApproval:
		evtType = schemas.EvSessionApproval
	case schemas.StatusCancelling:
		evtType = schemas.EvSessionCancelling
	case schemas.StatusCompleted:
		evtType = schemas.EvSessionCompleted
	case schemas.StatusFailed:
		evtType = schemas.EvSessionFailed
	default:
		return fmt.Errorf("unknown status: %s", to)
	}

	cp.Audit(ctx, sessionID, fmt.Sprintf("session.%s", to), map[string]any{
		"from": from,
		"to":   string(to),
	})
	return cp.emit(ctx, s, evtType)
}

// Recover loads non-terminal sessions from the State Store into memory.
// It is called during bootstrap after the store is initialized.
// Sessions are loaded with their last known status but do not emit events
// (the events were already emitted when they occurred).
// Returns the recovered sessions so callers can resume them via the coordinator.
func (cp *ControlPlane) Recover(ctx context.Context) ([]statestore.Session, error) {
	if cp.store == nil {
		return nil, nil
	}
	stored, err := cp.store.ListNonTerminalSessions(ctx)
	if err != nil {
		return nil, fmt.Errorf("recover sessions: %w", err)
	}
	cp.mu.Lock()
	for _, s := range stored {
		cp.sessions[s.ID] = &Session{
			ID:          s.ID,
			Status:      schemas.SessionStatus(s.Status),
			TaskID:      s.TaskID,
			Description: s.Description,
			CreatedAt:   s.CreatedAt,
			UpdatedAt:   s.UpdatedAt,
		}
	}
	cp.mu.Unlock()

	if len(stored) > 0 {
		log.Printf("controlplane: recovered %d non-terminal sessions", len(stored))
	}
	return stored, nil
}

func (cp *ControlPlane) GetSession(sessionID string) (*Session, bool) {
	cp.mu.RLock()
	s, ok := cp.sessions[sessionID]
	cp.mu.RUnlock()
	return s, ok
}

func (cp *ControlPlane) emit(ctx context.Context, s *Session, evtType schemas.EventType) error {
	evt := schemas.Event{
		ID:        fmt.Sprintf("%s-%d", s.ID, time.Now().UnixNano()),
		Type:      evtType,
		SessionID: s.ID,
		Timestamp: time.Now(),
		Payload: schemas.SessionPayload{
			SessionID: s.ID,
			TaskID:    s.TaskID,
			Status:    string(s.Status),
		},
	}
	subject := schemas.SessionEventSubject(s.ID, evtType)
	return cp.bus.Publish(ctx, subject, evt)
}
